/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package justFresh;

import entidades.LineaCompra;
import entidades.Producto;
import entidades.ProductoEmpacado;
import java.awt.Component;
import java.awt.Frame;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import static justFresh.Pnl_OrdenarPedido.lineasDeCompra;

/**
 *
 * @author Estudiante
 */
public class Dlg_CarritoCompra extends javax.swing.JDialog {
    
    /**
     * Creates new form jDlgInicioSesion
     */
    
    private DefaultTableModel modeloTabla;
    
    public Dlg_CarritoCompra(Component component) {
        super((Frame) SwingUtilities.getWindowAncestor(component), true);
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Productos.getModel();
        actualizarTabla();
        
        Btn_Eliminar.setEnabled(false);
    }
    
    private void actualizarTabla(){
        
        String[] Fila = new String[4];
        DecimalFormat df = new DecimalFormat("###,##0.00");

        modeloTabla.setRowCount(0);
        
        if(!lineasDeCompra.isEmpty()){
        
            for(LineaCompra lineaCompra : Pnl_OrdenarPedido.lineasDeCompra){

                Producto producto = lineaCompra.getProducto();

                Fila[0] = producto.getNombre();
                Fila[1] = producto instanceof ProductoEmpacado ? "Empacado" : "Preparado";
                Fila[2] = "₡ " + df.format(producto.getPrecio() * lineaCompra.getCantidad());
                Fila[3] = String.valueOf(lineaCompra.getCantidad());


                modeloTabla.addRow(Fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Productos = new javax.swing.JTable();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_Logo = new javax.swing.JLabel();
        Btn_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lineas de Compra");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        Btn_Volver.setText("Volver");
        Btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VolverActionPerformed(evt);
            }
        });

        Tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Productos);

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(200, 82, 98));
        Lbl_Encabezado.setText("Carrito!");

        Img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Isologo.png"))); // NOI18N

        Btn_Eliminar.setText("Eliminar Producto");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_Encabezado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_Logo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Lbl_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Img_Logo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Volver)
                    .addComponent(Btn_Eliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_Btn_VolverActionPerformed
    
    private void Tbl_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ProductosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 1){
            Btn_Eliminar.setEnabled(true);
        }
        if(evt.getClickCount() >= 2){
            
            Btn_Eliminar.setEnabled(false);

            String nombreProducto = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 0);
            String cantidadString = JOptionPane.showInputDialog(null, "Modifica la cantidad de " + nombreProducto + " que quieras en el carrito", "Actualizar carrito", JOptionPane.INFORMATION_MESSAGE);
            
            if(cantidadString != null && !cantidadString.isEmpty()){
                try{
                    
                    
                    for(LineaCompra Olinea : lineasDeCompra){
                        if(Olinea.getProducto().getNombre().equals(nombreProducto)){
                            
                            int cantidad = Integer.parseInt(cantidadString);
                            
                            if(cantidad <= 0){
                                JOptionPane.showMessageDialog(this, "Digite un numero mayor a 0", "Advertencia!", JOptionPane.WARNING_MESSAGE);
                                return;
                            }
                            
                            if(Olinea.getProducto() instanceof ProductoEmpacado){
                                
                                if(((ProductoEmpacado) Olinea.getProducto()).getCantidad() == 0){
                                    JOptionPane.showMessageDialog(this, "¡Producto se encuentra agotado!", "Advertencia!", JOptionPane.WARNING_MESSAGE);
                                    return;
                                }
                                
                                if(((ProductoEmpacado) Olinea.getProducto()).getCantidad() < cantidad){
                                    JOptionPane.showMessageDialog(this, "El restaurante no cuenta con " + cantidad + " " + Olinea.getProducto().getNombre(), "Advertencia!", JOptionPane.WARNING_MESSAGE);
                                    return;
                                }
                            }
                            
                            int indice = lineasDeCompra.indexOf(Olinea);
                            LineaCompra linea = new LineaCompra(cantidad, Olinea.getProducto());
                            lineasDeCompra.set(indice, linea);
                            
                            actualizarTabla();
                        }
                    }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Digite un formato valido.", "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e, "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_Tbl_ProductosMouseClicked

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:
        
        String nombreProducto = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 0);
        
        for(LineaCompra Olinea : lineasDeCompra){
            if(Olinea.getProducto().getNombre().equals(nombreProducto)){
                int indice = lineasDeCompra.indexOf(Olinea);
                lineasDeCompra.remove(indice);
                actualizarTabla();
                Btn_Eliminar.setEnabled(false);
                return;
            }
        }
        
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Volver;
    private javax.swing.JLabel Img_Logo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JTable Tbl_Productos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
