/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package justFresh;

import PersistenciaDAO.LineaCompraDAO;
import PersistenciaDAO.OrdenCompraDAO;
import PersistenciaDAO.ProductoDAO;
import entidades.LineaCompra;
import entidades.OrdenCompra;
import entidades.ProductoEmpacado;
import java.awt.Component;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Estudiante
 */
public class Dlg_Compra extends javax.swing.JDialog {
    
    /**
     * Creates new form jDlgInicioSesion
     */
    
    
    
    public Dlg_Compra(Component component) {
        super((Frame) SwingUtilities.getWindowAncestor(component), true);
        initComponents();
        
        Txa_OrdenCompra.setText(Pnl_OrdenarPedido.orden.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Volver = new javax.swing.JButton();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_Logo = new javax.swing.JLabel();
        Btn_Confirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txa_OrdenCompra = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orden de Compra");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        Btn_Volver.setText("Volver");
        Btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VolverActionPerformed(evt);
            }
        });

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(200, 82, 98));
        Lbl_Encabezado.setText("Finalizar compra!");

        Img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Isologo.png"))); // NOI18N

        Btn_Confirmar.setText("Confirmar Compra");
        Btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmarActionPerformed(evt);
            }
        });

        Txa_OrdenCompra.setEditable(false);
        Txa_OrdenCompra.setColumns(20);
        Txa_OrdenCompra.setRows(5);
        jScrollPane1.setViewportView(Txa_OrdenCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Confirmar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_Encabezado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                            .addComponent(Img_Logo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Lbl_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Img_Logo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Volver)
                    .addComponent(Btn_Confirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_Btn_VolverActionPerformed
    
    private void Btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmarActionPerformed
        // TODO add your handling code here:
        
        Pnl_OrdenarPedido.orden.setID(OrdenCompraDAO.obtenerSiguienteID());
        OrdenCompraDAO.insertarOrdenCompra(Pnl_OrdenarPedido.orden);
        LineaCompraDAO.insertarLineasCompras(Pnl_OrdenarPedido.orden);
        
        for(LineaCompra linea : Pnl_OrdenarPedido.orden.getLineasDeCompra()){
            if(linea.getProducto() instanceof ProductoEmpacado){
                ProductoDAO.updateCantidadProducto(linea.getProducto(), Pnl_OrdenarPedido.orden.getRestaurante().getID(), linea.getCantidad());
            }
        }
        
        
        JOptionPane.showMessageDialog(this, "¡Compra Realizada!\nN° de orden: " + Pnl_OrdenarPedido.orden.getID(), Pnl_OrdenarPedido.orden.getRestaurante().getNombre() + " | JustFresh!", JOptionPane.INFORMATION_MESSAGE);
        
        Pnl_OrdenarPedido.lineasDeCompra.clear();
        this.dispose();
        
    }//GEN-LAST:event_Btn_ConfirmarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Confirmar;
    private javax.swing.JButton Btn_Volver;
    private javax.swing.JLabel Img_Logo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JTextArea Txa_OrdenCompra;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
