/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package justFresh;

import PersistenciaDAO.PaisDAO;
import PersistenciaDAO.TarjetaDAO;
import PersistenciaDAO.UsuarioDAO;
import entidades.ETipoTarjeta;
import entidades.Pais;
import entidades.Tarjeta;
import entidades.Usuario;
import entidades.UsuarioAdministrador;
import entidades.UsuarioGerente;
import entidades.UsuarioRegular;
import java.time.LocalDate;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Estudiante
 */
public class Dlg_Registro extends javax.swing.JDialog {
    private final ImageIcon checkIcon = new ImageIcon("src/media/CheckIcon.png");
    private final ImageIcon errorIcon = new ImageIcon("src/media/ErrorIcon.png");
    private final ImageIcon eye_OpenIcon = new ImageIcon("src/media/Eye_Open.png");
    private final ImageIcon eye_ClosedIcon = new ImageIcon("src/media/Eye_Closed.png");
    private final ImageIcon unknown_Card = new ImageIcon("src/media/Unknown_Card.png");
    private final ImageIcon visa_Card = new ImageIcon("src/media/Visa_Card.png");
    private final ImageIcon master_Card = new ImageIcon("src/media/Master_Card.png");
    
    /**
     * Creates new form jDlgInicioSesion
     */
    public Dlg_Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        formatearCampos();
    }
    
    private void formatearCampos(){
        Rdb_UsuarioRegular.requestFocus();
        Img_VerificarNombre.setVisible(false);
        Img_VerificarCorreoElectronico.setVisible(false);
        Img_VerContrasena.setVisible(false);
        
        for(Pais pais: PaisDAO.selectALLPaises()){
            Cmb_PaisOrigen.addItem(pais);
        }
        
        LocalDate currentDate = LocalDate.now();
        
        SpinnerNumberModel newModelMonth = new SpinnerNumberModel(currentDate.getMonthValue(), currentDate.getMonthValue(), 12, 1);
        
        Spn_Mes.setModel(newModelMonth);
        
        SpinnerNumberModel newModelYear = new SpinnerNumberModel(currentDate.getYear(), currentDate.getYear(), 9999, 1);
        
        Spn_Ano.setModel(newModelYear);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btng_TipoUsuario = new javax.swing.ButtonGroup();
        Lbl_Encabezado = new javax.swing.JLabel();
        Lbl_Nombre = new javax.swing.JLabel();
        Txf_Nombre = new javax.swing.JTextField();
        Lbl_CorreoElectronico = new javax.swing.JLabel();
        Txf_CorreoElectronico = new javax.swing.JTextField();
        Img_VerificarNombre = new javax.swing.JLabel();
        Img_VerificarCorreoElectronico = new javax.swing.JLabel();
        Lbl_Contrasena = new javax.swing.JLabel();
        Psf_Contrasena = new javax.swing.JPasswordField();
        Btn_Volver = new javax.swing.JButton();
        Lbl_PaisOrigen = new javax.swing.JLabel();
        Img_Banner = new javax.swing.JLabel();
        Lbl_TipoUsuario = new javax.swing.JLabel();
        Rdb_UsuarioRegular = new javax.swing.JRadioButton();
        Rdb_GerenteRestaurante = new javax.swing.JRadioButton();
        Rdb_Administrador = new javax.swing.JRadioButton();
        Btn_Registrarse = new javax.swing.JButton();
        Sep_Tarjeta = new javax.swing.JSeparator();
        Lbl_NumeroTarjeta = new javax.swing.JLabel();
        Txf_NumeroTarjeta = new javax.swing.JTextField();
        Spn_Mes = new javax.swing.JSpinner();
        Lbl_FechaVencimiento = new javax.swing.JLabel();
        Sep_Fecha = new javax.swing.JSeparator();
        Spn_Ano = new javax.swing.JSpinner();
        Lbl_CodigoSeguridad = new javax.swing.JLabel();
        Img_VerContrasena = new javax.swing.JLabel();
        Cmb_PaisOrigen = new javax.swing.JComboBox<>();
        Psf_CodigoSeguridad = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Cuenta");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        Lbl_Encabezado.setText("Registro de cuenta!");

        Lbl_Nombre.setText("Nombre");

        Txf_Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txf_NombreFocusGained(evt);
            }
        });
        Txf_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txf_NombreKeyReleased(evt);
            }
        });

        Lbl_CorreoElectronico.setText("Correo Electronico");

        Txf_CorreoElectronico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Txf_CorreoElectronicoFocusGained(evt);
            }
        });
        Txf_CorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txf_CorreoElectronicoKeyReleased(evt);
            }
        });

        Img_VerificarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ErrorIcon.png"))); // NOI18N

        Img_VerificarCorreoElectronico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ErrorIcon.png"))); // NOI18N

        Lbl_Contrasena.setText("Contraseña");

        Psf_Contrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Psf_Contrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Psf_ContrasenaFocusGained(evt);
            }
        });

        Btn_Volver.setText("Volver");
        Btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VolverActionPerformed(evt);
            }
        });

        Lbl_PaisOrigen.setText("País de Origen");

        Img_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Banner_JDialog.png"))); // NOI18N

        Lbl_TipoUsuario.setText("Tipo de Usuario");

        Btng_TipoUsuario.add(Rdb_UsuarioRegular);
        Rdb_UsuarioRegular.setSelected(true);
        Rdb_UsuarioRegular.setText("Usuario Regular");
        Rdb_UsuarioRegular.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rdb_UsuarioRegularItemStateChanged(evt);
            }
        });

        Btng_TipoUsuario.add(Rdb_GerenteRestaurante);
        Rdb_GerenteRestaurante.setText("Gerente de Restaurante");

        Btng_TipoUsuario.add(Rdb_Administrador);
        Rdb_Administrador.setText("Administrador");

        Btn_Registrarse.setText("Registrarse");
        Btn_Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrarseActionPerformed(evt);
            }
        });

        Sep_Tarjeta.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Lbl_NumeroTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Unknown_Card.png"))); // NOI18N
        Lbl_NumeroTarjeta.setText("Numero de Tarjeta");
        Lbl_NumeroTarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Txf_NumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txf_NumeroTarjetaKeyReleased(evt);
            }
        });

        Spn_Mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        Lbl_FechaVencimiento.setText("Fecha de vencimiento");

        Sep_Fecha.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Spn_Ano.setModel(new javax.swing.SpinnerNumberModel(9999, null, 9999, 1));

        Lbl_CodigoSeguridad.setText("Codigo de Seguridad");

        Img_VerContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eye_Closed.png"))); // NOI18N
        Img_VerContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_VerContrasenaMouseClicked(evt);
            }
        });

        Psf_CodigoSeguridad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Psf_CodigoSeguridad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Psf_CodigoSeguridadFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Img_Banner)
                    .addComponent(Lbl_Encabezado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_TipoUsuario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Btn_Volver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_Registrarse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Rdb_UsuarioRegular)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Rdb_GerenteRestaurante, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Rdb_Administrador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sep_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbl_CodigoSeguridad)
                            .addComponent(Lbl_FechaVencimiento)
                            .addComponent(Txf_NumeroTarjeta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Spn_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sep_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spn_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Lbl_NumeroTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Psf_CodigoSeguridad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Nombre)
                            .addComponent(Lbl_PaisOrigen)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_CorreoElectronico, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lbl_Contrasena)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Psf_Contrasena)
                            .addComponent(Txf_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txf_CorreoElectronico)
                            .addComponent(Cmb_PaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Img_VerificarNombre)
                            .addComponent(Img_VerificarCorreoElectronico)
                            .addComponent(Img_VerContrasena))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Img_Banner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Cmb_PaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Img_VerificarCorreoElectronico)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lbl_Nombre))
                                    .addComponent(Img_VerificarNombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Txf_CorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_CorreoElectronico))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Psf_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lbl_Contrasena))
                            .addComponent(Img_VerContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lbl_PaisOrigen)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_TipoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rdb_UsuarioRegular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rdb_GerenteRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rdb_Administrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(Btn_Volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Registrarse)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_NumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txf_NumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lbl_FechaVencimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Sep_Fecha)
                                    .addComponent(Spn_Mes)
                                    .addComponent(Spn_Ano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(Lbl_CodigoSeguridad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Psf_CodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Sep_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_VolverActionPerformed

    private boolean validarCampos(){
        
        if(!validarNombre()){
            JOptionPane.showMessageDialog(this, "Digite un nombre valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!validarEmail()){
            JOptionPane.showMessageDialog(this, "Digite un email valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!validarContrasena()){
            JOptionPane.showMessageDialog(this, "Digite una contraseña valida.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if((!validarNumeroTarjeta() || validarTipoTarjeta() == null) && Rdb_UsuarioRegular.isSelected()){
            JOptionPane.showMessageDialog(this, "Digite una tarjeta bancaria valida. (VISA | Mastercard).", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;

        }
        if(!validarCodigoSeguridad() && Rdb_UsuarioRegular.isSelected()){
            JOptionPane.showMessageDialog(this, "Digite un codigo de seguridad valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private boolean validarNombre(){
        return !Txf_Nombre.getText().isEmpty() && Txf_Nombre.getText().length() <= 40;
    }
    
    private boolean validarEmail(){
        return UsuarioDAO.verificarDisponibilidadEmail(Txf_CorreoElectronico.getText()) && !Txf_CorreoElectronico.getText().isEmpty() && Txf_CorreoElectronico.getText().length() <= 320 && Txf_CorreoElectronico.getText().contains("@") && Txf_CorreoElectronico.getText().contains(".");
    }
    
    private boolean validarContrasena(){
        return Psf_Contrasena.getPassword().length > 0 && Psf_Contrasena.getPassword().length <= 50;
    }
    
    private boolean validarNumeroTarjeta(){
        
        String numero = Txf_NumeroTarjeta.getText();
        
        if(numero.isEmpty() || numero.length() != 16){
            return false;
        }
        
        int[] numTarjeta = new int[15];
        int numProvisional = 0, numProvisional2 = 0, suma = 0, validarDigitos = 0;
        
        for(int i = 14; i >= 0; i--){ 
            
            numProvisional = Character.getNumericValue(numero.charAt(i));
            
            if(i % 2 == 0){
                numProvisional2 = numProvisional * 2;
                suma = 0;
                while (numProvisional2 != 0) {
                    suma += numProvisional2 % 10;
                    numProvisional2 = numProvisional2 / 10;
                }
                numTarjeta[i] = suma;
            }else{
                numTarjeta[i] = numProvisional;
            }
        }
        
        
        for(int i = 14; i >= 0; i--){
            validarDigitos += numTarjeta[i];
        } 
        
        validarDigitos *= 9;
        
        return (validarDigitos % 10) == Character.getNumericValue(numero.charAt(15));
    }
    
    private ETipoTarjeta validarTipoTarjeta(){
        if(Txf_NumeroTarjeta.getText().startsWith("4") && validarNumeroTarjeta()){
            return ETipoTarjeta.VISA;
        }else if(Pattern.matches("^(51|52|53|54|55).*", Txf_NumeroTarjeta.getText()) && validarNumeroTarjeta()){
            return ETipoTarjeta.MASTERCARD;
        }else{
            return null;
        }
    }
    
    private boolean validarCodigoSeguridad(){
        int codigo = 0;
        
        try{
            if(Rdb_UsuarioRegular.isSelected()){
                codigo = Integer.parseInt(String.valueOf(Psf_CodigoSeguridad.getPassword()));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Digite un codigo de seguridad con formato valido.", "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
        }
        
        return codigo >= 1000 && codigo <= 9999;
    }
    
    private void Btn_RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrarseActionPerformed
        // TODO add your handling code here:
        
        if(validarCampos()){
            
            Usuario usuario;
            
            if(Rdb_Administrador.isSelected()){
                usuario = new UsuarioAdministrador(Txf_CorreoElectronico.getText().toLowerCase(), String.valueOf(Psf_Contrasena.getPassword()), Txf_Nombre.getText(),(Pais) Cmb_PaisOrigen.getSelectedItem(), true);
                
                UsuarioDAO.insertarUsuario(usuario);
            }else if(Rdb_GerenteRestaurante.isSelected()){
                usuario = new UsuarioGerente(Txf_CorreoElectronico.getText().toLowerCase(), String.valueOf(Psf_Contrasena.getPassword()), Txf_Nombre.getText(),(Pais) Cmb_PaisOrigen.getSelectedItem(), true);
                
                UsuarioDAO.insertarUsuario(usuario);
            }else{
                
                Tarjeta tarjeta = new Tarjeta(Long.parseLong(Txf_NumeroTarjeta.getText()), (int) Spn_Mes.getValue(), (int) Spn_Ano.getValue(), Integer.parseInt(String.valueOf(Psf_CodigoSeguridad.getPassword())), validarTipoTarjeta());
                usuario = new UsuarioRegular(Txf_CorreoElectronico.getText().toLowerCase(), String.valueOf(Psf_Contrasena.getPassword()), Txf_Nombre.getText(),(Pais) Cmb_PaisOrigen.getSelectedItem(), true, tarjeta);
                
                UsuarioDAO.insertarUsuario(usuario);
                TarjetaDAO.insertarTarjeta(tarjeta, usuario.getID());
            }
            
            principal.setUsuario(usuario);
            principal.actualizarInfoUsuario();
            this.dispose();
            
        }  
    }//GEN-LAST:event_Btn_RegistrarseActionPerformed

    private void Txf_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txf_NombreKeyReleased
        // TODO add your handling code here:
        if(validarNombre()){
            Img_VerificarNombre.setIcon(checkIcon);
        }else{
            Img_VerificarNombre.setIcon(errorIcon);
        }
    }//GEN-LAST:event_Txf_NombreKeyReleased

    private void Txf_NombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txf_NombreFocusGained
        // TODO add your handling code here:
        Img_VerificarNombre.setVisible(true);
    }//GEN-LAST:event_Txf_NombreFocusGained

    private void Txf_CorreoElectronicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Txf_CorreoElectronicoFocusGained
        // TODO add your handling code here:
        Img_VerificarCorreoElectronico.setVisible(true);
    }//GEN-LAST:event_Txf_CorreoElectronicoFocusGained

    private void Txf_CorreoElectronicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txf_CorreoElectronicoKeyReleased
        // TODO add your handling code here:
        if(validarEmail()){
            Img_VerificarCorreoElectronico.setIcon(checkIcon);
        }else{
            Img_VerificarCorreoElectronico.setIcon(errorIcon);
        }
    }//GEN-LAST:event_Txf_CorreoElectronicoKeyReleased

    private void Img_VerContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_VerContrasenaMouseClicked
        // TODO add your handling code here:
        
        if(Psf_Contrasena.getEchoChar() == '\u2022'){
            Psf_Contrasena.setEchoChar((char)0);
            Img_VerContrasena.setIcon(eye_OpenIcon);
        }else{
            Psf_Contrasena.setEchoChar('\u2022');
            Img_VerContrasena.setIcon(eye_ClosedIcon);
        }
        
    }//GEN-LAST:event_Img_VerContrasenaMouseClicked

    private void Psf_ContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Psf_ContrasenaFocusGained
        // TODO add your handling code here:
        Img_VerContrasena.setVisible(true);
    }//GEN-LAST:event_Psf_ContrasenaFocusGained

    private void Rdb_UsuarioRegularItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rdb_UsuarioRegularItemStateChanged
        // TODO add your handling code here:
        toggleCardForm(Rdb_UsuarioRegular.isSelected());    
    }//GEN-LAST:event_Rdb_UsuarioRegularItemStateChanged

    private void Txf_NumeroTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txf_NumeroTarjetaKeyReleased
        ETipoTarjeta tipo = validarTipoTarjeta();
        if (tipo == null) {
            Lbl_NumeroTarjeta.setIcon(unknown_Card);
        } else switch (tipo) {
            case VISA -> Lbl_NumeroTarjeta.setIcon(visa_Card);
            case MASTERCARD -> Lbl_NumeroTarjeta.setIcon(master_Card);
        }
    }//GEN-LAST:event_Txf_NumeroTarjetaKeyReleased

    private void Psf_CodigoSeguridadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Psf_CodigoSeguridadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Psf_CodigoSeguridadFocusGained

    private void toggleCardForm(boolean status){
        Sep_Tarjeta.setVisible(status);
        Lbl_NumeroTarjeta.setVisible(status);
        Txf_NumeroTarjeta.setVisible(status);
        Lbl_FechaVencimiento.setVisible(status);
        Spn_Mes.setVisible(status);
        Sep_Fecha.setVisible(status);
        Spn_Ano.setVisible(status);
        Lbl_CodigoSeguridad.setVisible(status);
        Psf_CodigoSeguridad.setVisible(status);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Registrarse;
    private javax.swing.JButton Btn_Volver;
    private javax.swing.ButtonGroup Btng_TipoUsuario;
    private javax.swing.JComboBox<Pais> Cmb_PaisOrigen;
    private javax.swing.JLabel Img_Banner;
    private javax.swing.JLabel Img_VerContrasena;
    private javax.swing.JLabel Img_VerificarCorreoElectronico;
    private javax.swing.JLabel Img_VerificarNombre;
    private javax.swing.JLabel Lbl_CodigoSeguridad;
    private javax.swing.JLabel Lbl_Contrasena;
    private javax.swing.JLabel Lbl_CorreoElectronico;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_FechaVencimiento;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_NumeroTarjeta;
    private javax.swing.JLabel Lbl_PaisOrigen;
    private javax.swing.JLabel Lbl_TipoUsuario;
    private javax.swing.JPasswordField Psf_CodigoSeguridad;
    private javax.swing.JPasswordField Psf_Contrasena;
    private javax.swing.JRadioButton Rdb_Administrador;
    private javax.swing.JRadioButton Rdb_GerenteRestaurante;
    private javax.swing.JRadioButton Rdb_UsuarioRegular;
    private javax.swing.JSeparator Sep_Fecha;
    private javax.swing.JSeparator Sep_Tarjeta;
    private javax.swing.JSpinner Spn_Ano;
    private javax.swing.JSpinner Spn_Mes;
    private javax.swing.JTextField Txf_CorreoElectronico;
    private javax.swing.JTextField Txf_Nombre;
    private javax.swing.JTextField Txf_NumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
