/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package justFresh;

import PersistenciaDAO.UsuarioDAO;
import entidades.Usuario;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import logicaDeNegocios.Usuario;
//import persistenciaDatos.PersistenciaUsuario;

/**
 *
 * @author Estudiante
 */
public class Dlg_InicioSesion extends javax.swing.JDialog {
    private int intentos = 3;
    private final ImageIcon eye_OpenIcon = new ImageIcon("src/media/Eye_Open.png");
    private final ImageIcon eye_ClosedIcon = new ImageIcon("src/media/Eye_Closed.png");
    
    /**
     * Creates new form jDlgInicioSesion
     */
    public Dlg_InicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Img_VerContrasena.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Encabezado = new javax.swing.JLabel();
        Lbl_CorreoElectronico = new javax.swing.JLabel();
        Txf_CorreoElectronico = new javax.swing.JTextField();
        Lbl_Contrasena = new javax.swing.JLabel();
        Btn_Volver = new javax.swing.JButton();
        Img_Banner = new javax.swing.JLabel();
        Btn_InicioSesion = new javax.swing.JButton();
        Img_VerContrasena = new javax.swing.JLabel();
        Psf_Contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de Cuenta");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        Lbl_Encabezado.setText("Inicio de sesión!");

        Lbl_CorreoElectronico.setText("Correo Electronico");

        Lbl_Contrasena.setText("Contraseña");

        Btn_Volver.setText("Volver");
        Btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VolverActionPerformed(evt);
            }
        });

        Img_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Banner_JDialog.png"))); // NOI18N

        Btn_InicioSesion.setText("Iniciar Sesión");
        Btn_InicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InicioSesionActionPerformed(evt);
            }
        });

        Img_VerContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Eye_Closed.png"))); // NOI18N
        Img_VerContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_VerContrasenaMouseClicked(evt);
            }
        });

        Psf_Contrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Psf_Contrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Psf_ContrasenaFocusGained(evt);
            }
        });
        Psf_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Psf_ContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Encabezado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_CorreoElectronico)
                                    .addComponent(Lbl_Contrasena))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Psf_Contrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txf_CorreoElectronico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_VerContrasena))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_InicioSesion))
                            .addComponent(Img_Banner))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Img_Banner)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_CorreoElectronico)
                    .addComponent(Txf_CorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Contrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_InicioSesion)
                            .addComponent(Btn_Volver))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Psf_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Img_VerContrasena))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_Btn_VolverActionPerformed

    private boolean validarCampos(){
        if(!validarEmail()){
            JOptionPane.showMessageDialog(this, "Digite un email.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!validarContrasena()){
            JOptionPane.showMessageDialog(this, "Digite una contraseña valida.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private boolean validarEmail(){
        return !Txf_CorreoElectronico.getText().isEmpty();
    }
    
    private boolean validarContrasena(){
        return Psf_Contrasena.getPassword().length > 0 && Psf_Contrasena.getPassword().length <= 50;
    }
    
    private void Btn_InicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InicioSesionActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            Usuario usuario = UsuarioDAO.selectUsuario(Txf_CorreoElectronico.getText().toLowerCase());
            if (usuario != null && usuario.isPermisoIngreso()) {
                //obtener la constraseña del control
                String contrasena = String.valueOf(Psf_Contrasena.getPassword());
                if (usuario.getContrasena().equals(contrasena)) {
                    principal.setUsuario(usuario);
                    principal.actualizarInfoUsuario();
                    this.dispose();
                }else{
                    intentos--;
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta. | " + intentos + " intentos restantes", "Inicio de Sesión Invalido!", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Cuenta no existente o deshabilitada.", "Inicio de Sesión Invalido!", JOptionPane.ERROR_MESSAGE);
            }

            if (intentos == 0) {
                UsuarioDAO.updateAccessUsuario(Txf_CorreoElectronico.getText(), false);
                JOptionPane.showMessageDialog(this, "Intentos maximos superados.", "La cuenta ha sido bloqueada!", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_Btn_InicioSesionActionPerformed

    private void Img_VerContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_VerContrasenaMouseClicked
        // TODO add your handling code here:

        if(Psf_Contrasena.getEchoChar() == '\u2022'){
            Psf_Contrasena.setEchoChar((char)0);
            Img_VerContrasena.setIcon(eye_OpenIcon);
        }else{
            Psf_Contrasena.setEchoChar('\u2022');
            Img_VerContrasena.setIcon(eye_ClosedIcon);
        }

    }//GEN-LAST:event_Img_VerContrasenaMouseClicked

    private void Psf_ContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Psf_ContrasenaFocusGained
        // TODO add your handling code here:
        Img_VerContrasena.setVisible(true);
    }//GEN-LAST:event_Psf_ContrasenaFocusGained

    private void Psf_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Psf_ContrasenaActionPerformed
        // TODO add your handling code here:
        Btn_InicioSesionActionPerformed(evt);
    }//GEN-LAST:event_Psf_ContrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_InicioSesion;
    private javax.swing.JButton Btn_Volver;
    private javax.swing.JLabel Img_Banner;
    private javax.swing.JLabel Img_VerContrasena;
    private javax.swing.JLabel Lbl_Contrasena;
    private javax.swing.JLabel Lbl_CorreoElectronico;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JPasswordField Psf_Contrasena;
    private javax.swing.JTextField Txf_CorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
