/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package justFresh;

import PersistenciaDAO.OrdenCompraDAO;
import entidades.EPermiso;
import entidades.Usuario;
import entidades.UsuarioAdministrador;
import entidades.UsuarioGerente;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import utilitarios.UtilitarioVentana;

/**
 *
 * @author Estudiante
 */
public class Frm_MenuPrincipal extends javax.swing.JFrame {
    
    private final ImageIcon AccountIcon = new ImageIcon("src/media/account_off.png");
    private final ImageIcon Account_LoggedIcon = new ImageIcon("src/media/account_on.png");
    
    /**
     * Creates new form Frm_MenuPrincipal
     */
    public Frm_MenuPrincipal() {
        initComponents();
        
        formatearElementos();
    }
    
    private void formatearElementos(){
        
        Mn_Cuenta.setText("Cuenta");
        MnI_CerrarSesion.setVisible(false);
        MnI_IniciarSesion.setVisible(true);
        MnI_Registro.setVisible(true);
        Mn_Cuenta.setIcon(AccountIcon);
        
        MnI_OrdenarPedido.setVisible(false);
        MnI_OrdenesRealizadas.setVisible(false);
        Mn_Reporteria.setVisible(false);
        Mn_Mantenimientos.setVisible(false);
        MnI_Paises.setVisible(false);
        MnI_Usuarios.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DP_Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn_Operaciones = new javax.swing.JMenu();
        MnI_OrdenarPedido = new javax.swing.JMenuItem();
        MnI_OrdenesRealizadas = new javax.swing.JMenuItem();
        MnI_Salir = new javax.swing.JMenuItem();
        Mn_Mantenimientos = new javax.swing.JMenu();
        MnI_Restaurantes = new javax.swing.JMenuItem();
        MnI_Productos = new javax.swing.JMenuItem();
        MnI_Paises = new javax.swing.JMenuItem();
        MnI_Usuarios = new javax.swing.JMenuItem();
        Mn_Reporteria = new javax.swing.JMenu();
        Mni_ReporteProductos = new javax.swing.JMenuItem();
        Mni_ReporteMejoresRestaurantes = new javax.swing.JMenuItem();
        Mni_ComprasRealizadas = new javax.swing.JMenuItem();
        Mn_Cuenta = new javax.swing.JMenu();
        MnI_Registro = new javax.swing.JMenuItem();
        MnI_IniciarSesion = new javax.swing.JMenuItem();
        MnI_CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DP_EscritorioLayout = new javax.swing.GroupLayout(DP_Escritorio);
        DP_Escritorio.setLayout(DP_EscritorioLayout);
        DP_EscritorioLayout.setHorizontalGroup(
            DP_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        DP_EscritorioLayout.setVerticalGroup(
            DP_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        Mn_Operaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Isologo.png"))); // NOI18N
        Mn_Operaciones.setText("Just Fresh!");
        Mn_Operaciones.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N

        MnI_OrdenarPedido.setText("Ordenar Pedido");
        MnI_OrdenarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_OrdenarPedidoActionPerformed(evt);
            }
        });
        Mn_Operaciones.add(MnI_OrdenarPedido);

        MnI_OrdenesRealizadas.setText("Ordenes Realizadas");
        MnI_OrdenesRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_OrdenesRealizadasActionPerformed(evt);
            }
        });
        Mn_Operaciones.add(MnI_OrdenesRealizadas);

        MnI_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnI_Salir.setText("Salir");
        MnI_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_SalirActionPerformed(evt);
            }
        });
        Mn_Operaciones.add(MnI_Salir);

        jMenuBar1.add(Mn_Operaciones);

        Mn_Mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Maintenance_Module.png"))); // NOI18N
        Mn_Mantenimientos.setText("Mantenimientos");

        MnI_Restaurantes.setText("Restaurantes");
        MnI_Restaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_RestaurantesActionPerformed(evt);
            }
        });
        Mn_Mantenimientos.add(MnI_Restaurantes);

        MnI_Productos.setText("Productos");
        MnI_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_ProductosActionPerformed(evt);
            }
        });
        Mn_Mantenimientos.add(MnI_Productos);

        MnI_Paises.setText("Paises");
        MnI_Paises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_PaisesActionPerformed(evt);
            }
        });
        Mn_Mantenimientos.add(MnI_Paises);

        MnI_Usuarios.setText("Usuarios");
        MnI_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_UsuariosActionPerformed(evt);
            }
        });
        Mn_Mantenimientos.add(MnI_Usuarios);

        jMenuBar1.add(Mn_Mantenimientos);

        Mn_Reporteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Report_Module.png"))); // NOI18N
        Mn_Reporteria.setText("Reportería");

        Mni_ReporteProductos.setText("Productos");
        Mni_ReporteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mni_ReporteProductosActionPerformed(evt);
            }
        });
        Mn_Reporteria.add(Mni_ReporteProductos);

        Mni_ReporteMejoresRestaurantes.setText("Mejores Restaurantes");
        Mni_ReporteMejoresRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mni_ReporteMejoresRestaurantesActionPerformed(evt);
            }
        });
        Mn_Reporteria.add(Mni_ReporteMejoresRestaurantes);

        Mni_ComprasRealizadas.setText("Compras Realizadas");
        Mni_ComprasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mni_ComprasRealizadasActionPerformed(evt);
            }
        });
        Mn_Reporteria.add(Mni_ComprasRealizadas);

        jMenuBar1.add(Mn_Reporteria);

        Mn_Cuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/account_off.png"))); // NOI18N
        Mn_Cuenta.setText("Cuenta");
        Mn_Cuenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        MnI_Registro.setText("Registrarse");
        MnI_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_RegistroActionPerformed(evt);
            }
        });
        Mn_Cuenta.add(MnI_Registro);

        MnI_IniciarSesion.setText("Iniciar Sesión");
        MnI_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_IniciarSesionActionPerformed(evt);
            }
        });
        Mn_Cuenta.add(MnI_IniciarSesion);

        MnI_CerrarSesion.setText("Cerrar Sesión");
        MnI_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnI_CerrarSesionActionPerformed(evt);
            }
        });
        Mn_Cuenta.add(MnI_CerrarSesion);

        jMenuBar1.add(Mn_Cuenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DP_Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DP_Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnI_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_SalirActionPerformed
        // TODO add your handling code here:
        
        formWindowClosing(new WindowEvent(this, WindowEvent.WINDOW_CLOSED));
        
    }//GEN-LAST:event_MnI_SalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea terminar la aplicación?","Atención",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(opcion == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        DP_Escritorio.setSize(this.getSize());
        
    }//GEN-LAST:event_formComponentShown

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        DP_Escritorio.setSize(this.getSize());
        //UtilitarioVentana.prueba(this, DP_Escritorio);
    }//GEN-LAST:event_formComponentResized

    private void inicioDeSesion(){
        Usuario usuario = principal.getUsuario();
        
        if(usuario != null){
            
            Mn_Cuenta.setText(usuario.getNombre());
            Mn_Cuenta.setIcon(Account_LoggedIcon);
            MnI_CerrarSesion.setVisible(true);
            MnI_Registro.setVisible(false);
            MnI_IniciarSesion.setVisible(false);
            
            if(usuario.getPermisos().contains(EPermiso.MANTENIMIENTO_RESTAURANTE)){
                Mn_Mantenimientos.setVisible(true);
                if(usuario instanceof UsuarioAdministrador){
                    MnI_Paises.setVisible(true);
                    MnI_Usuarios.setVisible(true);
                }
            }
            
            if(usuario.getPermisos().contains(EPermiso.REPORTERIA)){
                Mn_Reporteria.setVisible(true);
            }
            
            if(usuario.getPermisos().contains(EPermiso.ORDENAR_PRODUCTOS)){
                MnI_OrdenarPedido.setVisible(true);
                MnI_OrdenesRealizadas.setVisible(true);
            }
            
        }
    }
    
    private void MnI_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_RegistroActionPerformed
        // TODO add your handling code here:
        
        Dlg_Registro frmRegistroCuenta = new Dlg_Registro(this,true);
        frmRegistroCuenta.setLocationRelativeTo(null);
        frmRegistroCuenta.setVisible(true);
        
        inicioDeSesion();
        
    }//GEN-LAST:event_MnI_RegistroActionPerformed

    private void MnI_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_IniciarSesionActionPerformed
        // TODO add your handling code here:
        
        Dlg_InicioSesion frmInicioSesion = new Dlg_InicioSesion(this,true);
        frmInicioSesion.setLocationRelativeTo(null);
        frmInicioSesion.setVisible(true);
        
        inicioDeSesion();
    }//GEN-LAST:event_MnI_IniciarSesionActionPerformed

    private void MnI_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_CerrarSesionActionPerformed
        // TODO add your handling code here:
        
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión?", "Cierre de sesión", JOptionPane.YES_NO_OPTION);
        
        if(eleccion == JOptionPane.YES_OPTION){
            principal.setUsuario(null);
            formatearElementos();
            
            JInternalFrame[] frames = DP_Escritorio.getAllFrames();
            for (JInternalFrame frame : frames) {
                frame.dispose();
            }

            
        }
        
    }//GEN-LAST:event_MnI_CerrarSesionActionPerformed

    private void MnI_OrdenarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_OrdenarPedidoActionPerformed
        // TODO add your handling code here:
        
        UtilitarioVentana.centrarVentanaJFrame(this, "Orden de compra", new Pnl_OrdenarPedido(), DP_Escritorio);
        
    }//GEN-LAST:event_MnI_OrdenarPedidoActionPerformed

    private void MnI_RestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_RestaurantesActionPerformed
        // TODO add your handling code here:
        
        UtilitarioVentana.centrarVentanaJFrame(this, "Mantenimiento de Restaurantes", new Pnl_MantenimientoRestaurante(), DP_Escritorio);
        
    }//GEN-LAST:event_MnI_RestaurantesActionPerformed

    private void MnI_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_ProductosActionPerformed
        // TODO add your handling code here:
        
        if(principal.getUsuario() instanceof UsuarioGerente){
            if(((UsuarioGerente) principal.getUsuario()).getRestaurantes().isEmpty()){
                JOptionPane.showMessageDialog(this, "¡Usted no cuenta con ningún restaurante con productos!", "JustFresh!", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        UtilitarioVentana.centrarVentanaJFrame(this, "Mantenimiento de Productos", new Pnl_MantenimientoProducto(), DP_Escritorio);
        
    }//GEN-LAST:event_MnI_ProductosActionPerformed

    private void MnI_OrdenesRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_OrdenesRealizadasActionPerformed
        // TODO add your handling code here:
        
        if(OrdenCompraDAO.OrdenesDeUsuario(principal.getUsuario().getID()).isEmpty()){
            JOptionPane.showMessageDialog(this, "¡Usted no ha realizado ninguna orden de compra!", "JustFresh!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UtilitarioVentana.centrarVentanaJFrame(this, "Calificar Ordenes de compra", new Pnl_OrdenesRealizadas(), DP_Escritorio);
        
    }//GEN-LAST:event_MnI_OrdenesRealizadasActionPerformed

    private void Mni_ReporteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mni_ReporteProductosActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.centrarVentanaJFrame(this, "Reportería | Productos", new Pnl_ReporteProductos(), DP_Escritorio);
    }//GEN-LAST:event_Mni_ReporteProductosActionPerformed

    private void Mni_ReporteMejoresRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mni_ReporteMejoresRestaurantesActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.centrarVentanaJFrame(this, "Reportería | Mejores Restaurantes", new Pnl_ReporteMejoresRestaurantes(), DP_Escritorio);
    }//GEN-LAST:event_Mni_ReporteMejoresRestaurantesActionPerformed

    private void Mni_ComprasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mni_ComprasRealizadasActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.centrarVentanaJFrame(this, "Reportería | Compras Registradas", new Pnl_ReporteComprasRealizadas(), DP_Escritorio);
    }//GEN-LAST:event_Mni_ComprasRealizadasActionPerformed

    private void MnI_PaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_PaisesActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.centrarVentanaJFrame(this, "Mantenimiento de Paises", new Pnl_MantenimientoPaises(), DP_Escritorio);
    }//GEN-LAST:event_MnI_PaisesActionPerformed

    private void MnI_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnI_UsuariosActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.centrarVentanaJFrame(this, "Mantenimiento de Usuarios", new Pnl_MantenimientoUsuarios(), DP_Escritorio);
        
    }//GEN-LAST:event_MnI_UsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DP_Escritorio;
    private javax.swing.JMenuItem MnI_CerrarSesion;
    private javax.swing.JMenuItem MnI_IniciarSesion;
    private javax.swing.JMenuItem MnI_OrdenarPedido;
    private javax.swing.JMenuItem MnI_OrdenesRealizadas;
    private javax.swing.JMenuItem MnI_Paises;
    private javax.swing.JMenuItem MnI_Productos;
    private javax.swing.JMenuItem MnI_Registro;
    private javax.swing.JMenuItem MnI_Restaurantes;
    private javax.swing.JMenuItem MnI_Salir;
    private javax.swing.JMenuItem MnI_Usuarios;
    private javax.swing.JMenu Mn_Cuenta;
    private javax.swing.JMenu Mn_Mantenimientos;
    private javax.swing.JMenu Mn_Operaciones;
    private javax.swing.JMenu Mn_Reporteria;
    private javax.swing.JMenuItem Mni_ComprasRealizadas;
    private javax.swing.JMenuItem Mni_ReporteMejoresRestaurantes;
    private javax.swing.JMenuItem Mni_ReporteProductos;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
