/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.ProductoDAO;
import PersistenciaDAO.ResenaDAO;
import PersistenciaDAO.RestauranteDAO;
import PersistenciaDAO.UsuarioDAO;
import entidades.ETipoRestaurante;
import entidades.Restaurante;
import entidades.Usuario;
import entidades.UsuarioAdministrador;
import entidades.UsuarioGerente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_MantenimientoRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    
    public Pnl_MantenimientoRestaurante() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Restaurantes.getModel();
        formatearCampos();
    }
    
    private void formatearCampos(){
        Btn_Crear.setVisible(true);
     
        Btn_Actualizar.setVisible(false);
        Btn_Cancelar.setVisible(false);
        
        Cmb_TipoRestaurante.removeAllItems();
        Cmb_UsuarioGerente.setEnabled(true);
        
        if(principal.getUsuario() instanceof UsuarioAdministrador){
            
            Lbl_Gerente.setVisible(true);
            Cmb_UsuarioGerente.setVisible(true);
            Cmb_UsuarioGerente.removeAllItems();
            
        
            for(UsuarioGerente gerente : UsuarioDAO.selectUsuariosGerentes()){
                
                List<Restaurante> restaurantes = new ArrayList();

                for(Restaurante restaurante : RestauranteDAO.selectRestaurantes(gerente.getID())){

                    restaurante.setProductos(ProductoDAO.selectProductos(restaurante.getID()));
                    restaurante.setResenas(ResenaDAO.selectResenasRestaurante(restaurante.getID()));

                    restaurantes.add(restaurante);
                }

                ((UsuarioGerente) gerente).setRestaurantes(restaurantes);

                Cmb_UsuarioGerente.addItem(gerente);

                
            }
        }else{
            Cmb_UsuarioGerente.setVisible(false);
            Lbl_Gerente.setVisible(false);
        }
        
        for(ETipoRestaurante tipo : ETipoRestaurante.values()){
            Cmb_TipoRestaurante.addItem(tipo);
        }
        
        Txf_Nombre.setText("");
        Cmb_TipoRestaurante.setSelectedIndex(0);
        Txa_Localizacion.setText("");
        
        Tbl_Restaurantes.setEnabled(true);
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_CRUD_form = new javax.swing.JPanel();
        Lbl_CRUD = new javax.swing.JLabel();
        Lbl_Nombre = new javax.swing.JLabel();
        Txf_Nombre = new javax.swing.JTextField();
        Lbl_TipoRestaurante = new javax.swing.JLabel();
        Cmb_TipoRestaurante = new javax.swing.JComboBox<>();
        Lbl_Localizacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txa_Localizacion = new javax.swing.JTextArea();
        Btn_Crear = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Actualizar = new javax.swing.JButton();
        Lbl_Gerente = new javax.swing.JLabel();
        Cmb_UsuarioGerente = new javax.swing.JComboBox<>();
        Pnl_Restaurantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Restaurantes = new javax.swing.JTable();
        Lbl_Restaurantes = new javax.swing.JLabel();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_CRUD_form.setBackground(new java.awt.Color(234, 234, 234));

        Lbl_CRUD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_CRUD.setText("Mantenimiento de restaurante");

        Lbl_Nombre.setText("Nombre");

        Lbl_TipoRestaurante.setText("Tipo");

        Lbl_Localizacion.setText("Localización");

        Txa_Localizacion.setColumns(20);
        Txa_Localizacion.setRows(5);
        jScrollPane2.setViewportView(Txa_Localizacion);

        Btn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Create_Icon.png"))); // NOI18N
        Btn_Crear.setText("Añadir Restaurante");
        Btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cancel_Icon.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Update_Icon.png"))); // NOI18N
        Btn_Actualizar.setText("Actualizar Restaurante");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });

        Lbl_Gerente.setText("Usuario Gerente");

        Cmb_UsuarioGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_UsuarioGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_CRUD_formLayout = new javax.swing.GroupLayout(Pnl_CRUD_form);
        Pnl_CRUD_form.setLayout(Pnl_CRUD_formLayout);
        Pnl_CRUD_formLayout.setHorizontalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Nombre)
                            .addComponent(Lbl_TipoRestaurante)
                            .addComponent(Lbl_Localizacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cmb_TipoRestaurante, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Txf_Nombre)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                    .addComponent(Btn_Actualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addComponent(Lbl_CRUD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addComponent(Lbl_Gerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(Cmb_UsuarioGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_CRUD_formLayout.setVerticalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_CRUD)
                .addGap(18, 18, 18)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Gerente)
                    .addComponent(Cmb_UsuarioGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Nombre)
                    .addComponent(Txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_TipoRestaurante)
                    .addComponent(Cmb_TipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Localizacion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(Btn_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(Pnl_CRUD_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 360, 450));

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Tbl_Restaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "# de Productos", "☆"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Restaurantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_RestaurantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Restaurantes);
        Tbl_Restaurantes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tbl_Restaurantes.getColumnModel().getColumnCount() > 0) {
            Tbl_Restaurantes.getColumnModel().getColumn(3).setMaxWidth(20);
        }

        Lbl_Restaurantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Restaurantes.setText("Restaurantes registrados");

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Restaurantes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Restaurantes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 350, 450));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Restaurantes!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_square.png"))); // NOI18N
        add(Img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){
        
        if(!validarNombre()){
            JOptionPane.showMessageDialog(this, "Digite un nombre valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!validarDescripcion()){
            JOptionPane.showMessageDialog(this, "Digite una localización valida.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    //Mejora
    private void actualizarTabla(){
        
        UsuarioGerente usuario;
        
        if(principal.getUsuario() instanceof UsuarioGerente){
            usuario = (UsuarioGerente) principal.getUsuario();
        }else{
            usuario = (UsuarioGerente) Cmb_UsuarioGerente.getSelectedItem();
        }
        
        if(usuario != null){

            String[] Fila = new String[4];

            modeloTabla.setRowCount(0);

            for(Restaurante restaurante : usuario.getRestaurantes()){
                Fila[0] = restaurante.getNombre();
                Fila[1] = restaurante.getTipoRestaurante().toString();
                Fila[2] = String.valueOf(restaurante.getProductos().size());
                Fila[3] = String.valueOf(restaurante.getCalificacion());

                modeloTabla.addRow(Fila);
            }

        }else{
            JOptionPane.showMessageDialog(this, "Porfavor inicie sesión.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private boolean validarNombre(){
        return !Txf_Nombre.getText().isEmpty() && Txf_Nombre.getText().length() <= 35;
    }
    
    private boolean validarDescripcion(){
        return !Txa_Localizacion.getText().isEmpty() && Txa_Localizacion.getText().length() <= 75;
    }
    //Mejora
    private Restaurante obtenerRestauranteSeleccionado(){
        return RestauranteDAO.selectRestaurante((String) modeloTabla.getValueAt(Tbl_Restaurantes.getSelectedRow(), 0));
    }
    
    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        
        formatearCampos();
        
    }//GEN-LAST:event_Btn_CancelarActionPerformed
    
    private Restaurante obtenerRestauranteIngresado(){
        return new Restaurante(Txf_Nombre.getText(), Txa_Localizacion.getText(), (ETipoRestaurante) Cmb_TipoRestaurante.getSelectedItem());
    }
    
    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            
            UsuarioGerente usuario;
        
            if(principal.getUsuario() instanceof UsuarioGerente){
                usuario = (UsuarioGerente) principal.getUsuario();
            }else{
                usuario = (UsuarioGerente) Cmb_UsuarioGerente.getSelectedItem();
            }
            
            Restaurante restaurante = obtenerRestauranteIngresado();
            RestauranteDAO.updateRestaurante(obtenerRestauranteSeleccionado().getNombre(), usuario.getID(), restaurante);

            principal.actualizarInfoUsuario();

            formatearCampos();
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearActionPerformed
        // TODO add your handling code here:
        
        if(validarCampos()){
            
            UsuarioGerente usuario;
        
            if(principal.getUsuario() instanceof UsuarioGerente){
                usuario = (UsuarioGerente) principal.getUsuario();
            }else{
                usuario = (UsuarioGerente) Cmb_UsuarioGerente.getSelectedItem();
            }
        
            Restaurante restaurante = obtenerRestauranteIngresado();
                
            RestauranteDAO.insertarRestaurante(restaurante, usuario.getID());
            
            principal.actualizarInfoUsuario();

        }  
        
        formatearCampos();
    }//GEN-LAST:event_Btn_CrearActionPerformed

    private void Tbl_RestaurantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_RestaurantesMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1 && Tbl_Restaurantes.isEnabled()){
            
            Tbl_Restaurantes.setEnabled(false);
            Cmb_UsuarioGerente.setEnabled(false);
            
            Restaurante restaurante = obtenerRestauranteSeleccionado();
            
            Txf_Nombre.setText(restaurante.getNombre());
            Cmb_TipoRestaurante.setSelectedItem(restaurante.getTipoRestaurante());
            Txa_Localizacion.setText(restaurante.getLocalizacion());
            
            Btn_Crear.setVisible(false);
            Btn_Actualizar.setVisible(true);
            Btn_Cancelar.setVisible(true);
        }
        
    }//GEN-LAST:event_Tbl_RestaurantesMouseClicked

    private void Cmb_UsuarioGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_UsuarioGerenteActionPerformed
        // TODO add your handling code here:
        if(Cmb_UsuarioGerente.getItemCount() != 0){
            actualizarTabla();
        }
    }//GEN-LAST:event_Cmb_UsuarioGerenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Crear;
    private javax.swing.JComboBox<ETipoRestaurante> Cmb_TipoRestaurante;
    private javax.swing.JComboBox<Usuario> Cmb_UsuarioGerente;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_CRUD;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_Gerente;
    private javax.swing.JLabel Lbl_Localizacion;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_Restaurantes;
    private javax.swing.JLabel Lbl_TipoRestaurante;
    private javax.swing.JPanel Pnl_CRUD_form;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JTable Tbl_Restaurantes;
    private javax.swing.JTextArea Txa_Localizacion;
    private javax.swing.JTextField Txf_Nombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
