/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.ProductoDAO;
import PersistenciaDAO.ResenaDAO;
import PersistenciaDAO.RestauranteDAO;
import entidades.Producto;
import entidades.ProductoEmpacado;
import entidades.ProductoPreparado;
import entidades.Restaurante;
import entidades.UsuarioGerente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_MantenimientoProducto extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    
    public Pnl_MantenimientoProducto() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Productos.getModel();
        
        formatearCampos();
    }
    
    private void formatearCampos(){
        Btn_Crear.setVisible(true);
     
        Btn_Actualizar.setVisible(false);
        Btn_Cancelar.setVisible(false);
        
        Cmb_Restaurante.setEnabled(true);
        Cmb_Restaurante.removeAllItems();
        
        
        if(principal.getUsuario() instanceof UsuarioGerente){
            for(Restaurante restaurante : ((UsuarioGerente) principal.getUsuario()).getRestaurantes()){
                Cmb_Restaurante.addItem(restaurante);
            }
        }else{
            for(Restaurante restaurante : RestauranteDAO.selectRestaurantes()){
                restaurante.setResenas(ResenaDAO.selectResenasRestaurante(restaurante.getID()));
                Cmb_Restaurante.addItem(restaurante);
            }
        }
        
        
        
        Txf_Nombre.setText("");
        Rdb_Preparados.setSelected(true);
        Txf_Descripcion.setText("");
        Spn_Precio.setValue(0);
        Spn_TiempoPreparacion.setValue(1);
        Spn_Cantidad.setValue(1);
        Spn_Impuesto.setValue(0);
        
        Lbl_TiempoPreparacion.setVisible(true);
        Spn_TiempoPreparacion.setVisible(true);
        Lbl_Cantidad.setVisible(false);
        Spn_Cantidad.setVisible(false);
        Lbl_Impuesto.setVisible(false);
        Spn_Impuesto.setVisible(false);
        
        
        Tbl_Productos.setEnabled(true);
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btng_TipoProducto = new javax.swing.ButtonGroup();
        Pnl_CRUD_form = new javax.swing.JPanel();
        Lbl_CRUD = new javax.swing.JLabel();
        Lbl_Nombre = new javax.swing.JLabel();
        Txf_Nombre = new javax.swing.JTextField();
        Lbl_TipoRestaurante = new javax.swing.JLabel();
        Lbl_Localizacion = new javax.swing.JLabel();
        Btn_Crear = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Actualizar = new javax.swing.JButton();
        Rdb_Preparados = new javax.swing.JRadioButton();
        Rdb_Empacados = new javax.swing.JRadioButton();
        Spn_Precio = new javax.swing.JSpinner();
        Lbl_Precio = new javax.swing.JLabel();
        Lbl_TiempoPreparacion = new javax.swing.JLabel();
        Spn_TiempoPreparacion = new javax.swing.JSpinner();
        Lbl_Cantidad = new javax.swing.JLabel();
        Spn_Cantidad = new javax.swing.JSpinner();
        Lbl_Impuesto = new javax.swing.JLabel();
        Spn_Impuesto = new javax.swing.JSpinner();
        Lbl_Restaurante = new javax.swing.JLabel();
        Cmb_Restaurante = new javax.swing.JComboBox<>();
        Txf_Descripcion = new javax.swing.JTextField();
        Pnl_Restaurantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Productos = new javax.swing.JTable();
        Lbl_Producto = new javax.swing.JLabel();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_CRUD_form.setBackground(new java.awt.Color(234, 234, 234));

        Lbl_CRUD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_CRUD.setText("Mantenimiento de productos");

        Lbl_Nombre.setText("Nombre");

        Lbl_TipoRestaurante.setText("Tipo");

        Lbl_Localizacion.setText("Descripción");

        Btn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Create_Icon.png"))); // NOI18N
        Btn_Crear.setText("Añadir Producto");
        Btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cancel_Icon.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Update_Icon.png"))); // NOI18N
        Btn_Actualizar.setText("Actualizar Producto");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });

        Btng_TipoProducto.add(Rdb_Preparados);
        Rdb_Preparados.setSelected(true);
        Rdb_Preparados.setText("Preparados");
        Rdb_Preparados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Rdb_PreparadosItemStateChanged(evt);
            }
        });

        Btng_TipoProducto.add(Rdb_Empacados);
        Rdb_Empacados.setText("Empacados");

        Spn_Precio.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 25.0f));

        Lbl_Precio.setText("Precio ₡");

        Lbl_TiempoPreparacion.setText("Tiempo de preparación (m)");

        Spn_TiempoPreparacion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        Lbl_Cantidad.setText("Cantidad (unid)");

        Spn_Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        Lbl_Impuesto.setText("Impuesto %");

        Spn_Impuesto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        Lbl_Restaurante.setText("Restaurante");

        Cmb_Restaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_RestauranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_CRUD_formLayout = new javax.swing.GroupLayout(Pnl_CRUD_form);
        Pnl_CRUD_form.setLayout(Pnl_CRUD_formLayout);
        Pnl_CRUD_formLayout.setHorizontalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_TipoRestaurante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Precio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Rdb_Preparados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rdb_Empacados))
                            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Spn_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lbl_Restaurante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Localizacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cmb_Restaurante, javax.swing.GroupLayout.Alignment.TRAILING, 0, 178, Short.MAX_VALUE)
                            .addComponent(Txf_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txf_Descripcion)))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Impuesto)
                            .addComponent(Lbl_Cantidad)
                            .addComponent(Lbl_TiempoPreparacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Spn_TiempoPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Spn_Cantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Spn_Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_CRUD)
                            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Actualizar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_CRUD_formLayout.setVerticalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_CRUD)
                .addGap(12, 12, 12)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmb_Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Restaurante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Nombre)
                    .addComponent(Txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Localizacion)
                    .addComponent(Txf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Precio)
                    .addComponent(Spn_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_TipoRestaurante)
                    .addComponent(Rdb_Empacados)
                    .addComponent(Rdb_Preparados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_TiempoPreparacion)
                    .addComponent(Spn_TiempoPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Cantidad)
                    .addComponent(Spn_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Impuesto)
                    .addComponent(Spn_Impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Btn_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        add(Pnl_CRUD_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 450));

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Productos);
        Tbl_Productos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Lbl_Producto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Producto.setText("Productos en la carta");

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Producto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Producto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 370, 450));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Productos!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_square.png"))); // NOI18N
        add(Img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){
        
        if(!validarNombre()){
            JOptionPane.showMessageDialog(this, "Digite un nombre valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!validarDescripcion()){
            JOptionPane.showMessageDialog(this, "Digite una localización valida.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
       
    private boolean validarNombre(){
        return !Txf_Nombre.getText().isEmpty() && Txf_Nombre.getText().length() <= 35;
    }
    
    private boolean validarDescripcion(){
        return !Txf_Descripcion.getText().isEmpty() && Txf_Descripcion.getText().length() <= 75;
    }
    
    private int obtenerRestauranteID(){
        Restaurante restaurante = (Restaurante) Cmb_Restaurante.getSelectedItem();
        
        return restaurante.getID();
    }
    
    //Mejora
    private void actualizarTabla(){

        String[] Fila = new String[3];

        modeloTabla.setRowCount(0);

        
        for(Producto producto : ProductoDAO.selectProductos(obtenerRestauranteID())){
            Fila[0] = producto.getNombre();
            Fila[1] = producto instanceof ProductoEmpacado ? "Empacado" : "Preparado";
            Fila[2] = String.valueOf(producto.getPrecio());

            modeloTabla.addRow(Fila);
        }
        
    }
    
    private Producto obtenerProductoSeleccionado(){
        String[] Fila = new String[3];
        Fila[0] = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 0);
        Fila[1] = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 1);
        Fila[2] = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 2);

        String nombre = Fila[0];
        
        return ProductoDAO.selectProducto(nombre, obtenerRestauranteID());
    }
    
    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        
        formatearCampos();
        
    }//GEN-LAST:event_Btn_CancelarActionPerformed
    
    private Producto obtenerProductoIngresado(){
        if(Rdb_Empacados.isSelected()){
            int impuesto = (int) Spn_Impuesto.getValue();
            float impuestoPorcentaje = (float)impuesto / 10;
            
            return new ProductoEmpacado(Txf_Nombre.getText(), Txf_Descripcion.getText(), (float) Spn_Precio.getValue(), (int) Spn_Cantidad.getValue(),impuestoPorcentaje);
        }else{
            return new ProductoPreparado(Txf_Nombre.getText(), Txf_Descripcion.getText(), (float) Spn_Precio.getValue(),  (int) Spn_TiempoPreparacion.getValue());
        }
    }
    
    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            
            Producto producto = obtenerProductoIngresado();
            
            ProductoDAO.updateProducto(obtenerProductoSeleccionado().getNombre(), obtenerRestauranteID(), producto);

            principal.actualizarInfoUsuario();

            formatearCampos();
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearActionPerformed
        // TODO add your handling code here:
        
        if(validarCampos()){
        
            Producto producto = obtenerProductoIngresado();
                
            ProductoDAO.insertarProducto(producto, obtenerRestauranteID());
            
            principal.actualizarInfoUsuario();

        }  
        
        formatearCampos();
    }//GEN-LAST:event_Btn_CrearActionPerformed

    private void Tbl_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ProductosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1 && Tbl_Productos.isEnabled()){
            
            Tbl_Productos.setEnabled(false);
            
            Producto producto = obtenerProductoSeleccionado();
            
            Cmb_Restaurante.setEnabled(false);
            
            Txf_Nombre.setText(producto.getNombre());
            Txf_Descripcion.setText(producto.getDescripcion());
            Spn_Precio.setValue(producto.getPrecio());
            
            if(producto instanceof ProductoEmpacado){
                ProductoEmpacado productoEmpacado = (ProductoEmpacado) producto;
                
                Rdb_Empacados.setSelected(true);
                Spn_TiempoPreparacion.setValue(1);
                Spn_Cantidad.setValue(productoEmpacado.getCantidad());
                Spn_Impuesto.setValue( (int) (productoEmpacado.getImpuesto() * 10));
            }else{
                ProductoPreparado productoPreparado = (ProductoPreparado) producto;
                
                Rdb_Preparados.setSelected(true);
                Spn_TiempoPreparacion.setValue(productoPreparado.getTiempoPreparacion());
                Spn_Cantidad.setValue(1);
                Spn_Impuesto.setValue(0);
            }
            
            Btn_Crear.setVisible(false);
            Btn_Actualizar.setVisible(true);
            Btn_Cancelar.setVisible(true);
        }
        
    }//GEN-LAST:event_Tbl_ProductosMouseClicked

    private void Cmb_RestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_RestauranteActionPerformed
        // TODO add your handling code here:
        if(Cmb_Restaurante.getItemCount() > 0){
            actualizarTabla();
        }
    }//GEN-LAST:event_Cmb_RestauranteActionPerformed

    private void Rdb_PreparadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Rdb_PreparadosItemStateChanged
        // TODO add your handling code here:
        
        if(Rdb_Preparados.isSelected()){
            
            Lbl_TiempoPreparacion.setVisible(true);
            Spn_TiempoPreparacion.setVisible(true);
            Lbl_Cantidad.setVisible(false);
            Spn_Cantidad.setVisible(false);
            Lbl_Impuesto.setVisible(false);
            Spn_Impuesto.setVisible(false);
            
        }else{
            
            Lbl_TiempoPreparacion.setVisible(false);
            Spn_TiempoPreparacion.setVisible(false);
            Lbl_Cantidad.setVisible(true);
            Spn_Cantidad.setVisible(true);
            Lbl_Impuesto.setVisible(true);
            Spn_Impuesto.setVisible(true);
            
        }
    }//GEN-LAST:event_Rdb_PreparadosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Crear;
    private javax.swing.ButtonGroup Btng_TipoProducto;
    private javax.swing.JComboBox<Restaurante> Cmb_Restaurante;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_CRUD;
    private javax.swing.JLabel Lbl_Cantidad;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_Impuesto;
    private javax.swing.JLabel Lbl_Localizacion;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_Precio;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JLabel Lbl_Restaurante;
    private javax.swing.JLabel Lbl_TiempoPreparacion;
    private javax.swing.JLabel Lbl_TipoRestaurante;
    private javax.swing.JPanel Pnl_CRUD_form;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JRadioButton Rdb_Empacados;
    private javax.swing.JRadioButton Rdb_Preparados;
    private javax.swing.JSpinner Spn_Cantidad;
    private javax.swing.JSpinner Spn_Impuesto;
    private javax.swing.JSpinner Spn_Precio;
    private javax.swing.JSpinner Spn_TiempoPreparacion;
    private javax.swing.JTable Tbl_Productos;
    private javax.swing.JTextField Txf_Descripcion;
    private javax.swing.JTextField Txf_Nombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
