/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.PaisDAO;
import entidades.Pais;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_MantenimientoPaises extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    
    public Pnl_MantenimientoPaises() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Paises.getModel();
        
        formatearCampos();
    }
    
    private void formatearCampos(){
        Btn_Crear.setVisible(true);
     
        Btn_Actualizar.setVisible(false);
        Btn_Cancelar.setVisible(false); 
        
        Txf_Nombre.setText("");

        Spn_Codigo.setValue(1);

        Tbl_Paises.setEnabled(true);
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btng_TipoProducto = new javax.swing.ButtonGroup();
        Pnl_CRUD_form = new javax.swing.JPanel();
        Lbl_CRUD = new javax.swing.JLabel();
        Lbl_Nombre = new javax.swing.JLabel();
        Txf_Nombre = new javax.swing.JTextField();
        Btn_Crear = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Actualizar = new javax.swing.JButton();
        Lbl_Codigo = new javax.swing.JLabel();
        Spn_Codigo = new javax.swing.JSpinner();
        Pnl_Restaurantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Paises = new javax.swing.JTable();
        Lbl_Producto = new javax.swing.JLabel();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_CRUD_form.setBackground(new java.awt.Color(234, 234, 234));

        Lbl_CRUD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_CRUD.setText("Mantenimiento de paises");

        Lbl_Nombre.setText("Nombre");

        Btn_Crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Create_Icon.png"))); // NOI18N
        Btn_Crear.setText("Añadir País");
        Btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CrearActionPerformed(evt);
            }
        });

        Btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Cancel_Icon.png"))); // NOI18N
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });

        Btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Update_Icon.png"))); // NOI18N
        Btn_Actualizar.setText("Actualizar País");
        Btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActualizarActionPerformed(evt);
            }
        });

        Lbl_Codigo.setText("Codigo");

        Spn_Codigo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout Pnl_CRUD_formLayout = new javax.swing.GroupLayout(Pnl_CRUD_form);
        Pnl_CRUD_form.setLayout(Pnl_CRUD_formLayout);
        Pnl_CRUD_formLayout.setHorizontalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addComponent(Lbl_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_CRUD)
                            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_Crear, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(Btn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addComponent(Lbl_Codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Spn_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Pnl_CRUD_formLayout.setVerticalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_CRUD)
                .addGap(18, 18, 18)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Nombre)
                    .addComponent(Txf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Codigo)
                    .addComponent(Spn_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(Btn_Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        add(Pnl_CRUD_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 450));

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Tbl_Paises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_PaisesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Paises);
        Tbl_Paises.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tbl_Paises.getColumnModel().getColumnCount() > 0) {
            Tbl_Paises.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        Lbl_Producto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Producto.setText("Paises registrados");

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Producto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Producto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 370, 450));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Paises!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_square.png"))); // NOI18N
        add(Img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){
        
        if(!validarNombre()){
            JOptionPane.showMessageDialog(this, "Digite un nombre valido.", "Advertencia!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
       
    private boolean validarNombre(){
        return !Txf_Nombre.getText().isEmpty() && Txf_Nombre.getText().length() <= 25;
    }
    
    
    //Mejora
    private void actualizarTabla(){

        String[] Fila = new String[3];

        modeloTabla.setRowCount(0);

        
        for(Pais pais : PaisDAO.selectALLPaises()){
            Fila[0] = String.valueOf(pais.getID());
            Fila[1] = pais.getNombre();
            Fila[2] = String.valueOf(pais.getCodigo());

            modeloTabla.addRow(Fila);
        }
        
    }
    
    private Pais obtenerPaisSeleccionado(){
        
        return PaisDAO.selectPais(Integer.parseInt((String) modeloTabla.getValueAt(Tbl_Paises.getSelectedRow(), 0)));
    }
    
    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        // TODO add your handling code here:
        
        formatearCampos();
        
    }//GEN-LAST:event_Btn_CancelarActionPerformed
    
    private Pais obtenerPaisIngresado(){
        return new Pais((int) Spn_Codigo.getValue(), Txf_Nombre.getText());
    }
    
    private void Btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActualizarActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            
            Pais pais = obtenerPaisSeleccionado();
            
            PaisDAO.updatePais(obtenerPaisIngresado(), pais.getID());

            formatearCampos();
        }
    }//GEN-LAST:event_Btn_ActualizarActionPerformed

    private void Btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CrearActionPerformed
        // TODO add your handling code here:
        
        if(validarCampos()){
        
            Pais pais = obtenerPaisIngresado();
                
            PaisDAO.insertarPais(pais);

        }  
        
        formatearCampos();
    }//GEN-LAST:event_Btn_CrearActionPerformed

    private void Tbl_PaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_PaisesMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1 && Tbl_Paises.isEnabled()){
            
            Tbl_Paises.setEnabled(false);
            
            Pais pais = obtenerPaisSeleccionado();

            Txf_Nombre.setText(pais.getNombre());
            Spn_Codigo.setValue(pais.getCodigo());
            
            Btn_Crear.setVisible(false);
            Btn_Actualizar.setVisible(true);
            Btn_Cancelar.setVisible(true);
        }
        
    }//GEN-LAST:event_Tbl_PaisesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actualizar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Crear;
    private javax.swing.ButtonGroup Btng_TipoProducto;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_CRUD;
    private javax.swing.JLabel Lbl_Codigo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Nombre;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JPanel Pnl_CRUD_form;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JSpinner Spn_Codigo;
    private javax.swing.JTable Tbl_Paises;
    private javax.swing.JTextField Txf_Nombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
