/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.ProductoDAO;
import PersistenciaDAO.RestauranteDAO;
import entidades.ETipoRestaurante;
import entidades.Producto;
import entidades.Restaurante;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_ReporteProductos extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    
    public Pnl_ReporteProductos() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Productos.getModel();
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btng_TipoProducto = new javax.swing.ButtonGroup();
        Pnl_Restaurantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Productos = new javax.swing.JTable();
        Lbl_Producto = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_Encabezado = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripción", "Restaurante", "Tipo de Restaurante", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Productos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(Tbl_Productos);
        Tbl_Productos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tbl_Productos.getColumnModel().getColumnCount() > 0) {
            Tbl_Productos.getColumnModel().getColumn(0).setMaxWidth(50);
            Tbl_Productos.getColumnModel().getColumn(2).setMinWidth(250);
        }

        Lbl_Producto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Producto.setText("Productos registrados");

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_small.png"))); // NOI18N

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Img_logo)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Producto)
                    .addComponent(Img_logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1090, 510));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Reportería!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTabla(){

        String[] Fila = new String[6];
        DecimalFormat df = new DecimalFormat("###,##0.00");

        modeloTabla.setRowCount(0);
        
        for(ETipoRestaurante tipo : ETipoRestaurante.values()){
            for(Restaurante restaurante : RestauranteDAO.selectRestaurantes(tipo)){
                for(Producto producto : ProductoDAO.selectProductos(restaurante.getID())){
                    Fila[0] = String.valueOf(producto.getID(restaurante.getID()));
                    Fila[1] = producto.getNombre();
                    Fila[2] = producto.getDescripcion();
                    Fila[3] = restaurante.getNombre();
                    Fila[4] = tipo.toString();
                    Fila[5] = "₡ " + df.format(producto.getPrecio());

                    modeloTabla.addRow(Fila);
                    
                }
            }
        } 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Btng_TipoProducto;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JTable Tbl_Productos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
