/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.ProductoDAO;
import PersistenciaDAO.ResenaDAO;
import PersistenciaDAO.RestauranteDAO;
import entidades.ETipoRestaurante;
import entidades.LineaCompra;
import entidades.OrdenCompra;
import entidades.Producto;
import entidades.ProductoEmpacado;
import entidades.ProductoPreparado;
import entidades.Restaurante;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_OrdenarPedido extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_OrdenarPedido
     */
    
    public static List<LineaCompra> lineasDeCompra;
    public static OrdenCompra orden;
    private DefaultTableModel modeloTabla;
    
    public Pnl_OrdenarPedido() {
        initComponents();
        lineasDeCompra = new ArrayList();
        modeloTabla = (DefaultTableModel) Tbl_Productos.getModel();
        formatearCampos();
        
    }
    
    private void formatearCampos(){
        
        toggleCompra(false);
        
        Cmb_TipoRestaurante.removeAllItems();
        
        for(ETipoRestaurante tipo : ETipoRestaurante.values()){
            Cmb_TipoRestaurante.addItem(tipo);
            
        }
        
    }
    
    public void toggleCompra(boolean estado){
        Cmb_TipoRestaurante.setEnabled(!estado);
        Cmb_Restaurantes.setEnabled(!estado);
        Btn_Carrito.setEnabled(estado);
        Btn_Pagar.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Encabezado = new javax.swing.JLabel();
        Img_Fondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Img_Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Productos = new javax.swing.JTable();
        Lbl_Encabezado1 = new javax.swing.JLabel();
        Txf_Busqueda = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Btn_Pagar = new javax.swing.JButton();
        Btn_Carrito = new javax.swing.JButton();
        Lbl_TipoRestaurante = new javax.swing.JLabel();
        Cmb_TipoRestaurante = new javax.swing.JComboBox<>();
        Cmb_Restaurantes = new javax.swing.JComboBox<>();
        Lbl_Restaurantes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 89, 87));
        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(196, 68, 86)));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Realizar compra!");

        Img_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Fondo.jpeg"))); // NOI18N

        Img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Isologo.png"))); // NOI18N

        Tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción", "Tipo", "Precio", "Tiempo de preparación", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Productos);

        Lbl_Encabezado1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        Lbl_Encabezado1.setForeground(new java.awt.Color(200, 82, 98));
        Lbl_Encabezado1.setText("Productos disponibles!");

        Txf_Busqueda.setToolTipText("");
        Txf_Busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txf_BusquedaKeyReleased(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Search.png"))); // NOI18N
        jLabel1.setText("Buscar un producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Lbl_Encabezado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Txf_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Img_Logo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Img_Logo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_Encabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Txf_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        Btn_Pagar.setText("Pagar");
        Btn_Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PagarActionPerformed(evt);
            }
        });

        Btn_Carrito.setText("Carrito de compras");
        Btn_Carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CarritoActionPerformed(evt);
            }
        });

        Lbl_TipoRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_TipoRestaurante.setText("1. Selecciona el tipo de restaurante");

        Cmb_TipoRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_TipoRestauranteActionPerformed(evt);
            }
        });

        Cmb_Restaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_RestaurantesActionPerformed(evt);
            }
        });

        Lbl_Restaurantes.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Restaurantes.setText("2. Selecciona tu restaurante favorito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Img_Fondo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Encabezado)
                                    .addComponent(Lbl_TipoRestaurante)
                                    .addComponent(Lbl_Restaurantes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cmb_TipoRestaurante, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cmb_Restaurantes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Pagar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Carrito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(23, 23, 23)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Lbl_TipoRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cmb_TipoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_Restaurantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cmb_Restaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Carrito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Img_Fondo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CarritoActionPerformed
        // TODO add your handling code here:
        
        Dlg_CarritoCompra frmCarrito = new Dlg_CarritoCompra(this);
        frmCarrito.setLocationRelativeTo(null);
        frmCarrito.setVisible(true);
        
        if(lineasDeCompra.isEmpty()){
            toggleCompra(false);
        }
        
    }//GEN-LAST:event_Btn_CarritoActionPerformed

    private void Cmb_TipoRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_TipoRestauranteActionPerformed
        // TODO add your handling code here:
        
        List<Restaurante> restaurantes = RestauranteDAO.selectRestaurantes((ETipoRestaurante) Cmb_TipoRestaurante.getSelectedItem());
        
        Cmb_Restaurantes.removeAllItems();
        
        for(Restaurante restaurante : restaurantes){
            restaurante.setResenas(ResenaDAO.selectResenasRestaurante(restaurante.getID()));
            Cmb_Restaurantes.addItem(restaurante);
            
        }
    }//GEN-LAST:event_Cmb_TipoRestauranteActionPerformed

    private int obtenerRestauranteID(){
        Restaurante restaurante = (Restaurante) Cmb_Restaurantes.getSelectedItem();
        
        return restaurante.getID();
    }
    
    private void actualizarTabla(){

        String[] Fila = new String[6];

        modeloTabla.setRowCount(0);
        DecimalFormat df = new DecimalFormat("###,##0.00");

        
        for(Producto producto : ProductoDAO.selectProductos(obtenerRestauranteID())){
            Fila[0] = producto.getNombre();
            Fila[1] = producto.getDescripcion();
            Fila[3] = "₡ " + df.format(producto.getPrecio());
            if(producto instanceof ProductoEmpacado){
                Fila[2] = "Empacado";
                Fila[4] = "N/A";
                Fila[5] = String.valueOf(((ProductoEmpacado) producto).getCantidad());
            }else{
                Fila[2] = "Preparado";
                Fila[4] = String.valueOf(((ProductoPreparado) producto).getTiempoPreparacion()) + " minutos";
                Fila[5] = "N/A";
            }
            
            
            modeloTabla.addRow(Fila);
        }
        
    }
    
    private void actualizarTablaPorBusqueda(String busqueda){

        String[] Fila = new String[6];

        modeloTabla.setRowCount(0);
        DecimalFormat df = new DecimalFormat("###,##0.00");

        
        for(Producto producto : ProductoDAO.selectProductos(obtenerRestauranteID())){
            if((producto.getNombre().toUpperCase()).contains(busqueda.toUpperCase())){
                Fila[0] = producto.getNombre();
                Fila[1] = producto.getDescripcion();
                Fila[3] = "₡ " + df.format(producto.getPrecio());
                if(producto instanceof ProductoEmpacado){
                    Fila[2] = "Empacado";
                    Fila[4] = "N/A";
                    Fila[5] = String.valueOf(((ProductoEmpacado) producto).getCantidad());
                }else{
                    Fila[2] = "Preparado";
                    Fila[4] = String.valueOf(((ProductoPreparado) producto).getTiempoPreparacion()) + " minutos";
                    Fila[5] = "N/A";
                }


                modeloTabla.addRow(Fila);
            }
        }
    }
    
    private Producto obtenerProductoSeleccionado(){

        String nombre = (String) modeloTabla.getValueAt(Tbl_Productos.getSelectedRow(), 0);
        
        return ProductoDAO.selectProducto(nombre, obtenerRestauranteID());
    }
    
    private void Tbl_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_ProductosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1 && Tbl_Productos.isEnabled()){


            Producto producto = obtenerProductoSeleccionado();
            Restaurante restaurante = (Restaurante) Cmb_Restaurantes.getSelectedItem();
            
            String cantidadString = JOptionPane.showInputDialog(null, "Ingresa la cantidad de " + producto.getNombre() + " que quieras añadir al carrito", "Restaurante | " + restaurante.getNombre(), JOptionPane.INFORMATION_MESSAGE);

            if(cantidadString != null && !cantidadString.isEmpty()){
                try{
                    int cantidad = Integer.parseInt(cantidadString);
                    
                    if(cantidad <= 0){
                        JOptionPane.showMessageDialog(this, "Digite un numero mayor a 0", "Advertencia!", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    
                    if(producto instanceof ProductoEmpacado){
                        
                        if(((ProductoEmpacado) producto).getCantidad() == 0){
                            JOptionPane.showMessageDialog(this, "¡Producto se encuentra agotado!", "Advertencia!", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        
                        if(((ProductoEmpacado) producto).getCantidad() < cantidad){
                            JOptionPane.showMessageDialog(this, "El restaurante no cuenta con " + cantidad + " " + producto.getNombre(), "Restaurante | " + restaurante.getNombre(), JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                        
                    }
                    
                    LineaCompra linea = new LineaCompra(cantidad, producto);
                    
                    for(LineaCompra Olinea : lineasDeCompra){
                        if(Olinea.getProducto().getNombre().equals(producto.getNombre())){
                            JOptionPane.showMessageDialog(this, "Se ha modificado la orden existente con " + cantidad + " " + producto.getNombre(), "Restaurante | " + restaurante.getNombre(), JOptionPane.INFORMATION_MESSAGE);
                            
                            int indice = lineasDeCompra.indexOf(Olinea);
                            lineasDeCompra.set(indice, linea);
                            
                            return;
                        }
                    }
                    
                    toggleCompra(true);
                    lineasDeCompra.add(linea);
                    JOptionPane.showMessageDialog(this, "¡Producto añadido en el carrito con exito!", "Restaurante | " + restaurante.getNombre(), JOptionPane.INFORMATION_MESSAGE);
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Digite un formato valido.", "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e, "Ha sucedido un error!", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            
        }

    }//GEN-LAST:event_Tbl_ProductosMouseClicked

    private void Cmb_RestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_RestaurantesActionPerformed
        // TODO add your handling code here:
        
        if(Cmb_Restaurantes.getItemCount() > 0){
            actualizarTabla();
        }
        
    }//GEN-LAST:event_Cmb_RestaurantesActionPerformed

    private void Txf_BusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txf_BusquedaKeyReleased
        // TODO add your handling code here:
        
        if(!Txf_Busqueda.getText().isEmpty()){
            actualizarTablaPorBusqueda(Txf_Busqueda.getText());
        }else{
            actualizarTabla();
        }
        
    }//GEN-LAST:event_Txf_BusquedaKeyReleased

    private void Btn_PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PagarActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        
        orden = new OrdenCompra(sdf.format(date), principal.getUsuario(), (Restaurante) Cmb_Restaurantes.getSelectedItem(), lineasDeCompra);
        
        Dlg_Compra frmCompra = new Dlg_Compra(this);
        frmCompra.setLocationRelativeTo(null);
        frmCompra.setVisible(true);
        
        if(lineasDeCompra.isEmpty()){
            toggleCompra(false);
        }
    }//GEN-LAST:event_Btn_PagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Carrito;
    private javax.swing.JButton Btn_Pagar;
    private javax.swing.JComboBox<Restaurante> Cmb_Restaurantes;
    private javax.swing.JComboBox<ETipoRestaurante> Cmb_TipoRestaurante;
    private javax.swing.JLabel Img_Fondo;
    private javax.swing.JLabel Img_Logo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_Encabezado1;
    private javax.swing.JLabel Lbl_Restaurantes;
    private javax.swing.JLabel Lbl_TipoRestaurante;
    private javax.swing.JTable Tbl_Productos;
    private javax.swing.JTextField Txf_Busqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
