/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.OrdenCompraDAO;
import PersistenciaDAO.ResenaDAO;
import entidades.OrdenCompra;
import entidades.Resena;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_OrdenesRealizadas extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    private final ImageIcon EstrellaTrue = new ImageIcon("src/media/Estrella_true.png");
    private final ImageIcon EstrellaFalse = new ImageIcon("src/media/Estrella_false.png");
    
    public Pnl_OrdenesRealizadas() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_OrdenCompra.getModel();
        toggleCamposPuntuacion(false);
        actualizarTabla();
    }
    
    
    private void toggleCamposPuntuacion(boolean estado){
        
        Lbl_Header2.setVisible(estado);
        Lbl_Puntuacion.setVisible(estado);
        Img_Estrella1.setVisible(estado);
        Img_Estrella2.setVisible(estado);
        Img_Estrella3.setVisible(estado);
        Img_Estrella4.setVisible(estado);
        Img_Estrella5.setVisible(estado);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_CRUD_form = new javax.swing.JPanel();
        Lbl_Header = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_OrdenCompra = new javax.swing.JTable();
        Lbl_Puntuacion = new javax.swing.JLabel();
        Lbl_Header2 = new javax.swing.JLabel();
        Img_Estrella1 = new javax.swing.JLabel();
        Img_Estrella2 = new javax.swing.JLabel();
        Img_Estrella3 = new javax.swing.JLabel();
        Img_Estrella4 = new javax.swing.JLabel();
        Img_Estrella5 = new javax.swing.JLabel();
        Pnl_Restaurantes = new javax.swing.JPanel();
        Lbl_Detalle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txa_Detalle = new javax.swing.JTextArea();
        Lbl_Encabezado = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_CRUD_form.setBackground(new java.awt.Color(234, 234, 234));

        Lbl_Header.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Header.setText("Ordenes de compra");

        Tbl_OrdenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° de orden", "Restaurante", "Fecha", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_OrdenCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_OrdenCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbl_OrdenCompra);

        Lbl_Puntuacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lbl_Puntuacion.setText("Puntuación");

        Lbl_Header2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Header2.setText("Calificar la orden N°");

        Img_Estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estrella_false.png"))); // NOI18N
        Img_Estrella1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_Estrella1MouseClicked(evt);
            }
        });

        Img_Estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estrella_false.png"))); // NOI18N
        Img_Estrella2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_Estrella2MouseClicked(evt);
            }
        });

        Img_Estrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estrella_false.png"))); // NOI18N
        Img_Estrella3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_Estrella3MouseClicked(evt);
            }
        });

        Img_Estrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estrella_false.png"))); // NOI18N
        Img_Estrella4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_Estrella4MouseClicked(evt);
            }
        });

        Img_Estrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Estrella_false.png"))); // NOI18N
        Img_Estrella5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Img_Estrella5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Pnl_CRUD_formLayout = new javax.swing.GroupLayout(Pnl_CRUD_form);
        Pnl_CRUD_form.setLayout(Pnl_CRUD_formLayout);
        Pnl_CRUD_formLayout.setHorizontalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Header)
                            .addComponent(Lbl_Header2)
                            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                                .addComponent(Lbl_Puntuacion)
                                .addGap(18, 18, 18)
                                .addComponent(Img_Estrella1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_Estrella2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_Estrella3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_Estrella4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Img_Estrella5)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_CRUD_formLayout.setVerticalGroup(
            Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Header)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Header2)
                .addGroup(Pnl_CRUD_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Img_Estrella1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Img_Estrella2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Img_Estrella3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Img_Estrella4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Img_Estrella5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pnl_CRUD_formLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Lbl_Puntuacion)))
                .addGap(19, 19, 19))
        );

        add(Pnl_CRUD_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 360, 450));

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Lbl_Detalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Detalle.setText("Detalle del pedido");

        Txa_Detalle.setEditable(false);
        Txa_Detalle.setColumns(20);
        Txa_Detalle.setRows(5);
        jScrollPane1.setViewportView(Txa_Detalle);

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Detalle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_Detalle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 350, 450));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Calificá tus pedidos!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_square.png"))); // NOI18N
        add(Img_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTabla(){

        String[] Fila = new String[4];
        DecimalFormat df = new DecimalFormat("###,##0.00");
        modeloTabla.setRowCount(0);

        
        for(OrdenCompra ordenCompra : OrdenCompraDAO.OrdenesDeUsuario(principal.getUsuario().getID())){
            Fila[0] = String.valueOf(ordenCompra.getID());
            Fila[1] = ordenCompra.getRestaurante().getNombre();
            Fila[2] = ordenCompra.getFechaCompra();
            Fila[3] = "₡ " + df.format(ordenCompra.calcularTotal());

            modeloTabla.addRow(Fila);
        }
        
    }
    
    private OrdenCompra obtenerOrdenCompraSeleccionada(){

        int ID = Integer.parseInt((String) modeloTabla.getValueAt(Tbl_OrdenCompra.getSelectedRow(), 0));
        
        return OrdenCompraDAO.selectOrdenCompra(ID);
        
    }
    
    private void Tbl_OrdenCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_OrdenCompraMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1){

            OrdenCompra orden = obtenerOrdenCompraSeleccionada();
            
            Txa_Detalle.setText(orden.toString());
            toggleCamposPuntuacion(true);
            Lbl_Header2.setText("Calificar la orden N° " + orden.getID());
            
            Resena resenaActual = ResenaDAO.ObtenerResena(orden.getID(), orden.getUsuario().getID());
            
            if(resenaActual != null){
                actualizarEstrellas(resenaActual.getCalificacion());
            }else{
                resetEstrellas();
            }
            
            
        }
        
    }//GEN-LAST:event_Tbl_OrdenCompraMouseClicked

    private void actualizarCalificacion(int calificacion){
        
        OrdenCompra orden = obtenerOrdenCompraSeleccionada();
            
        if(ResenaDAO.ObtenerResena(orden.getID(), orden.getUsuario().getID()) != null){
            
            ResenaDAO.updateResena(new Resena(orden, calificacion));
        }else{
            ResenaDAO.insertarResena(new Resena(orden, calificacion));
        }
        
    }
    
    private void resetEstrellas(){
        Img_Estrella1.setIcon(EstrellaFalse);
        Img_Estrella2.setIcon(EstrellaFalse);
        Img_Estrella3.setIcon(EstrellaFalse);
        Img_Estrella4.setIcon(EstrellaFalse);
        Img_Estrella5.setIcon(EstrellaFalse);
    }
    
    private void actualizarEstrellas(int calificacion){
        resetEstrellas();
        
        switch (calificacion) {
            case 5:
                Img_Estrella5.setIcon(EstrellaTrue);
            case 4:
                Img_Estrella4.setIcon(EstrellaTrue);
            case 3:
                Img_Estrella3.setIcon(EstrellaTrue);
            case 2:
                Img_Estrella2.setIcon(EstrellaTrue);
            case 1:
                Img_Estrella1.setIcon(EstrellaTrue);
                break;
        }
        
    }
    
    
    private void Img_Estrella1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_Estrella1MouseClicked
        // TODO add your handling code here:
        actualizarEstrellas(1);
        actualizarCalificacion(1);
    }//GEN-LAST:event_Img_Estrella1MouseClicked

    private void Img_Estrella2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_Estrella2MouseClicked
        // TODO add your handling code here:
        actualizarEstrellas(2);
        actualizarCalificacion(2);
    }//GEN-LAST:event_Img_Estrella2MouseClicked

    private void Img_Estrella3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_Estrella3MouseClicked
        // TODO add your handling code here:
        actualizarEstrellas(3);
        actualizarCalificacion(3);
    }//GEN-LAST:event_Img_Estrella3MouseClicked

    private void Img_Estrella4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_Estrella4MouseClicked
        // TODO add your handling code here:
        actualizarEstrellas(4);
        actualizarCalificacion(4);
    }//GEN-LAST:event_Img_Estrella4MouseClicked

    private void Img_Estrella5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Img_Estrella5MouseClicked
        // TODO add your handling code here:
        actualizarEstrellas(5);
        actualizarCalificacion(5);
    }//GEN-LAST:event_Img_Estrella5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img_Estrella1;
    private javax.swing.JLabel Img_Estrella2;
    private javax.swing.JLabel Img_Estrella3;
    private javax.swing.JLabel Img_Estrella4;
    private javax.swing.JLabel Img_Estrella5;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_Detalle;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_Header;
    private javax.swing.JLabel Lbl_Header2;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Puntuacion;
    private javax.swing.JPanel Pnl_CRUD_form;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JTable Tbl_OrdenCompra;
    private javax.swing.JTextArea Txa_Detalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
