/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package justFresh;

import PersistenciaDAO.UsuarioDAO;
import entidades.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés Bolaños
 */
public class Pnl_MantenimientoUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_MantenimientoRestaurante
     */
    
    private DefaultTableModel modeloTabla;
    
    public Pnl_MantenimientoUsuarios() {
        initComponents();
        modeloTabla = (DefaultTableModel) Tbl_Usuarios.getModel();
        
        actualizarTabla();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btng_TipoProducto = new javax.swing.ButtonGroup();
        Pnl_Restaurantes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Usuarios = new javax.swing.JTable();
        Lbl_Producto = new javax.swing.JLabel();
        Img_logo = new javax.swing.JLabel();
        Lbl_Encabezado = new javax.swing.JLabel();
        Lbl_MarcoVentana = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 68, 86));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Restaurantes.setBackground(new java.awt.Color(234, 234, 234));

        Tbl_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Email", "Ingreso Permitido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl_Usuarios.setColumnSelectionAllowed(true);
        Tbl_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Usuarios);
        Tbl_Usuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tbl_Usuarios.getColumnModel().getColumnCount() > 0) {
            Tbl_Usuarios.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        Lbl_Producto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lbl_Producto.setText("Usuarios Registrados");

        Img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logo_small.png"))); // NOI18N

        javax.swing.GroupLayout Pnl_RestaurantesLayout = new javax.swing.GroupLayout(Pnl_Restaurantes);
        Pnl_Restaurantes.setLayout(Pnl_RestaurantesLayout);
        Pnl_RestaurantesLayout.setHorizontalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addGroup(Pnl_RestaurantesLayout.createSequentialGroup()
                        .addComponent(Lbl_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Img_logo)))
                .addContainerGap())
        );
        Pnl_RestaurantesLayout.setVerticalGroup(
            Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RestaurantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_Producto)
                    .addComponent(Img_logo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(Pnl_Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1060, 510));

        Lbl_Encabezado.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        Lbl_Encabezado.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Encabezado.setText("Usuarios!");
        add(Lbl_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, -1, 16));
        add(Lbl_MarcoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 20, 10));
    }// </editor-fold>//GEN-END:initComponents
    
    //Mejora
    private void actualizarTabla(){

        String[] Fila = new String[4];

        modeloTabla.setRowCount(0);

        
        for(Usuario usuario : UsuarioDAO.selectUsuarios()){
            Fila[0] = String.valueOf(usuario.getID());
            Fila[1] = usuario.getNombre();
            Fila[2] = usuario.getCorreoElectronico();
            Fila[3] = usuario.isPermisoIngreso() ? "Sí" : "No";

            modeloTabla.addRow(Fila);
        }
        
    }
    
    private Usuario obtenerUsuarioSeleccionado(){
        
        return UsuarioDAO.selectUsuario(Integer.parseInt((String) modeloTabla.getValueAt(Tbl_Usuarios.getSelectedRow(), 0)));
    }
    
    private void Tbl_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_UsuariosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() >= 1){
            
            Usuario usuario = obtenerUsuarioSeleccionado();
            
            int ingreso = JOptionPane.showConfirmDialog(null, "¿Desea permitir el ingreso de " + usuario.getNombre() + " ?", "Actualizar permisos de ingreso", JOptionPane.YES_NO_OPTION);

            if(ingreso != -1){
                UsuarioDAO.updateAccessUsuario(usuario.getCorreoElectronico(), ingreso == JOptionPane.YES_OPTION);
            }
            
            actualizarTabla();
        }
        
    }//GEN-LAST:event_Tbl_UsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Btng_TipoProducto;
    private javax.swing.JLabel Img_logo;
    private javax.swing.JLabel Lbl_Encabezado;
    private javax.swing.JLabel Lbl_MarcoVentana;
    private javax.swing.JLabel Lbl_Producto;
    private javax.swing.JPanel Pnl_Restaurantes;
    private javax.swing.JTable Tbl_Usuarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
